apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    path: /var/export/nexus
    server: ose3-master.example.com

